version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: smy1gonlie6kbze1enznyj/app
    steps:
      - run:
          name: Run a Step
          command: echo "Hi I'm on a Container Runner!"

workflows:
  build-workflow:
    jobs:
      - build
