version: 2.1

jobs:
  runner-test:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:wB8CzHbEjCFfcZZRQ173Xk+LMxPkx4mx2R9l4YM"  # Replace with the actual fingerprint
      - run:
          name: "Runner Test"
          command: |
            ssh -i ~/.ssh/circleci_rsa ragad@13.71.64.2 'echo "Hello, I am on Runners!"'
      - run:
          name: "Copy files to home folder and run install.sh"
          command: |
            scp -i ~/.ssh/circleci_rsa -r ./* ragad@13.71.64.2:/home/raga
            ssh -i ~/.ssh/circleci_rsa ragad@13.71.64.2 'cd /home/raga && ./install.sh'

  deploy-helm:
    docker:
      - image: cimg/base:2022.01
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Deploy Helm Charts
          command: ./install.sh

workflows:
  version: 2
  build:
    jobs:
      - runner-test
      - deploy-helm:
          requires:
            - runner-test
          filters:
            branches:
              only:
                - main
