jobs:
  runner-test:
    machine: true
    resource_class: smy1gonlie6kbze1enznyj/app
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:wB8CzHbEjCFfcZZRQp173Xk+LMxPkx4mx2R9l4YM0l0"  # Replace with the actual fingerprint
      - run:
          name: "Runner Test"
          command: ssh -i ~/.ssh/circleci_rsa raga@13.71.64.229 'echo "Hi, I'm on Runners!"'

