version: 2.1

jobs:
  runner-test:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:wB8CzHbEjCFfcZZRQp173Xk+LMxPkx4mx2R9l4YM0l0"  # Replace with the actual fingerprint
      - run:
          name: "Runner Test"
          command: |
            ssh -i ~/.ssh/circleci_rsa raga@13.71.64.229 'echo "Hello, I am on Runners!"'
      - run:
          name: "Install Helm"
          command: |
            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
            chmod 700 get_helm.sh
            ./get_helm.sh
      - run:
          name: "Run install.sh"
          command: |
            ./install.sh

  deploy-helm:
    docker:
      - image: cimg/base:2022.01  # Replace with a suitable Docker image for Helm
    working_directory: /app
    steps:
      - checkout
      - run:
          name: "Deploy Helm Charts"
          command: |
            ./install.sh

workflows:
  version: 2
  build:
    jobs:
      - runner-test
      - deploy-helm:
          requires:
            - runner-test
          filters:
            branches:
              only:
                - main
