version: 2.1

jobs:
  runner-test:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:wB8CzHbEjCFfcZZRQp173Xk+LMxPkx4mx2R9l4YM0l0"  # Replace with the actual fingerprint
      - run:
          name: "Runner Test"
          command: |
            ssh -i ~/.ssh/circleci_rsa raga@13.71.64.229 'echo "Hello, I am on Runners!"'
      - run:
          name: "Copy files to home folder and run install.sh"
          command: |
            scp -i ~/.ssh/circleci_rsa -r ./* raga@13.71.64.229:/home/raga
            ssh -i ~/.ssh/circleci_rsa raga@13.71.64.229 'cd /home/raga && ./install.sh'

workflows:
  version: 2
  build:
    jobs:
      - runner-test
      - deploy-helm:
          requires:
            - runner-test
          filters:
            branches:
              only:
                - main
